const { faker, setSeedFaker } = require('#config/faker.config.js');
const Account = require('#models/account.model.js');
const Product = require('#models/product.model.js');
const { thumbUrls, regularUrls } = require('./img.js');

const tags = [
  'Thân thiện với môi trường',
  'Tự làm',
  'Hữu cơ',
  'Giảm giá',
  'Sản phẩm mới',
  'Có thể tùy chỉnh',
  'Phải có',
  'Sáng tạo',
  'Công nghệ',
  'Thể thao',
  'Tài liệu',
  'Dụng cụ học tập',
  'Trang trí'
];

const descriptions = [
  'Sản phẩm chất lượng cao',
  'Được làm từ vật liệu bền bỉ',
  'Thiết kế hiện đại và tinh tế',
  'Thích hợp cho mọi nhu cầu sử dụng',
  'Tiện lợi và dễ sử dụng',
  'Sản phẩm đa năng',
  'Đảm bảo an toàn tuyệt đối',
  'Tiết kiệm năng lượng hiệu quả',
  'Màu sắc sang trọng và thanh lịch',
  'Phù hợp với mọi không gian',
  'Chất liệu mềm mại, dễ chịu',
  'Dễ dàng vệ sinh và bảo quản',
  'Thích hợp sử dụng trong gia đình',
  'Sản phẩm có độ bền cao',
  'Dễ dàng lắp đặt và sử dụng',
  'Tạo sự thoải mái tối đa',
  'Chống thấm nước tuyệt vời',
  'Mang lại hiệu quả sử dụng lâu dài',
  'Kích thước nhỏ gọn, dễ mang theo',
  'Sản phẩm thân thiện với môi trường',
  'Tăng cường độ bền và hiệu suất',
  'Thích hợp cho mọi lứa tuổi',
  'Thiết kế nhỏ gọn, tiện lợi',
  'Sản phẩm bảo vệ sức khỏe',
  'Màu sắc tươi sáng, bắt mắt',
  'Hỗ trợ người sử dụng hiệu quả',
  'Chắc chắn và bền bỉ',
  'Tiện dụng trong mọi tình huống',
  'Mang lại sự tiện lợi tối đa',
  'Dễ dàng điều chỉnh theo nhu cầu',
  'Chất lượng vượt trội, giá cả hợp lý',
  'Giúp tiết kiệm thời gian và công sức',
  'Được ưa chuộng trên thị trường',
  'Đảm bảo hiệu quả sử dụng tối ưu',
  'Sản phẩm thời trang, sang trọng',
  'Chống trơn trượt hiệu quả',
  'Tối ưu hóa không gian sử dụng',
  'Mang lại sự hài lòng tuyệt đối',
  'Lựa chọn hoàn hảo cho gia đình',
  'Sản phẩm được bảo hành dài hạn',
  'Sử dụng công nghệ hiện đại',
  'Công dụng vượt trội, dễ sử dụng',
  'Được nhiều người tiêu dùng tin tưởng',
  'Dễ dàng thay thế và bảo dưỡng',
  'Giải pháp tối ưu cho mọi vấn đề',
  'Thiết kế đẹp mắt và tiện lợi',
  'Sản phẩm mang lại sự hài lòng cho khách hàng',
  'Lý tưởng cho những ai yêu thích sự đơn giản',
  'Sản phẩm chất lượng với giá cả phải chăng',
  'Giúp nâng cao hiệu quả công việc',
  'Sử dụng vật liệu cao cấp, an toàn',
  'Sản phẩm có thể tái sử dụng',
  'Mang lại sự tiện lợi trong công việc',
  'Chức năng thông minh và tiện dụng',
  'Thích hợp với nhiều mục đích sử dụng',
  'Kết cấu chắc chắn, bền vững',
  'Giảm thiểu chi phí và công sức',
  'Dễ dàng mang theo khi đi du lịch',
  'Phù hợp với mọi gia đình',
  'Chất liệu an toàn, thân thiện với sức khỏe',
  'Giúp bảo vệ sức khỏe người sử dụng',
  'Tiết kiệm không gian hiệu quả',
  'Chắc chắn là sự lựa chọn lý tưởng',
  'Thiết kế đơn giản, dễ sử dụng',
  'Sản phẩm phù hợp với mọi nhu cầu',
  'Chắc chắn sẽ làm hài lòng khách hàng',
  'Giải pháp tối ưu cho không gian sống',
  'Chất lượng sản phẩm vượt trội',
  'Mới mẻ và hiện đại',
  'Công nghệ tiên tiến giúp nâng cao hiệu suất',
  'Đảm bảo độ bền và độ chính xác cao',
  'Lựa chọn hoàn hảo cho gia đình bạn',
  'Công năng vượt trội, sử dụng dễ dàng',
  'Tiết kiệm năng lượng và thời gian',
  'Chất liệu cao cấp, đảm bảo chất lượng',
  'Dễ dàng tùy chỉnh theo nhu cầu',
  'Mang lại sự thuận tiện cho người sử dụng',
  'Chất lượng ổn định và đáng tin cậy',
  'Giúp tiết kiệm chi phí hiệu quả',
  'Thiết kế nhỏ gọn, dễ sử dụng',
  'Mang lại sự thoải mái trong sử dụng',
  'Lựa chọn thông minh cho gia đình',
  'Thiết kế sáng tạo, đột phá',
  'Phù hợp cho mọi không gian sống',
  'Chất liệu mềm mại, êm ái',
  'Lắp đặt nhanh chóng và dễ dàng',
  'Được làm từ vật liệu thân thiện với môi trường',
  'Sản phẩm bền bỉ và đẹp mắt',
  'Mang lại sự tiện nghi cho mọi người',
  'Thiết kế đa dạng, phù hợp với nhiều phong cách',
  'Dễ dàng vận hành và bảo trì',
  'Tăng cường hiệu quả sử dụng hàng ngày',
  'Chức năng thông minh và tiện lợi',
  'Được sản xuất với công nghệ tiên tiến',
  'Sản phẩm chất lượng, giá trị cao',
  'Thích hợp cho các mục đích sử dụng khác nhau',
  'Sử dụng dễ dàng và hiệu quả',
  'Giúp tối ưu hóa công việc hàng ngày',
  'Sản phẩm với độ bền vượt trội',
  'Công nghệ hiện đại cho hiệu suất tối đa',
  'Mang lại trải nghiệm sử dụng tuyệt vời',
  'Sản phẩm tốt, phù hợp với mọi nhu cầu',
  'Giảm thiểu chi phí bảo trì và thay thế',
  'Lựa chọn hợp lý cho mọi gia đình',
  'Sản phẩm dễ dàng vận hành và bảo dưỡng',
  'Giải pháp tuyệt vời cho mọi nhu cầu sử dụng',
  'Sản phẩm sáng tạo, độc đáo',
  'Chắc chắn là sự lựa chọn đáng tin cậy',
  'Dễ dàng tương thích với mọi thiết bị',
  'Chất liệu an toàn và thân thiện với người sử dụng',
  'Giúp bảo vệ sức khỏe và sự an toàn',
  'Sản phẩm lý tưởng cho việc sử dụng hàng ngày',
  'Mang lại giá trị sử dụng lâu dài'
];

const adj = [
  'chất lượng',
  'đẹp',
  'bền',
  'hiện đại',
  'sang trọng',
  'tiện lợi',
  'nhỏ gọn',
  'tiết kiệm',
  'mới',
  'dễ sử dụng',
  'sang trọng',
  'mềm mại',
  'chắc chắn',
  'đa năng',
  'tiện ích',
  'thông minh',
  'vượt trội',
  'chắc chắn',
  'tinh tế',
  'an toàn',
  'độc đáo',
  'nổi bật',
  'hấp dẫn',
  'thời trang',
  'năng động',
  'tiết kiệm không gian',
  'mạnh mẽ',
  'đẳng cấp',
  'tối ưu',
  'sạch sẽ',
  'bền vững',
  'dễ dàng',
  'thanh lịch',
  'công nghệ cao',
  'tinh xảo',
  'tiện dụng',
  'vừa vặn',
  'sáng tạo',
  'thời thượng',
  'lộng lẫy',
  'sạch',
  'thực tế',
  'mạnh mẽ',
  'thông minh',
  'hữu ích',
  'thân thiện',
  'nhẹ nhàng',
  'lạ mắt',
  'khoa học',
  'hấp dẫn',
  'chống nước',
  'chống trượt',
  'dễ bảo quản',
  'lớn',
  'gọn gàng',
  'chính xác',
  'tiết kiệm năng lượng',
  'sáng bóng',
  'mượt mà',
  'ngon',
  'cực kỳ tiện lợi',
  'gần gũi',
  'tiện nghi',
  'sử dụng dễ dàng',
  'tiết kiệm thời gian',
  'cao cấp',
  'tốt',
  'hoàn hảo',
  'cao cấp',
  'tốc độ cao',
  'khỏe khoắn',
  'thân thiện với môi trường',
  'sắc nét',
  'chắc chắn',
  'ổn định',
  'lôi cuốn',
  'mượt',
  'đầy đủ',
  'trẻ trung',
  'sang trọng',
  'chất lượng cao',
  'dễ dàng lắp đặt',
  'bảo vệ',
  'tận tâm',
  'chính hãng',
  'phong cách',
  'tinh tế',
  'an tâm',
  'tốt cho sức khỏe',
  'thật sự tuyệt vời',
  'kháng khuẩn',
  'dễ sử dụng',
  'hiệu quả',
  'sắc sảo',
  'sẵn sàng',
  'đảm bảo',
  'gọn nhẹ',
  'đầy đủ',
  'đảm bảo chất lượng',
  'dễ dàng thay thế',
  'đột phá',
  'tự động',
  'mới mẻ',
  'tinh tế',
  'đầy đủ chức năng',
  'đảm bảo an toàn'
];

const noun = [
  'Sách giáo khoa',
  'Bảng trắng',
  'Phấn',
  'Bút',
  'Vở',
  'Máy tính cầm tay',
  'Máy chiếu',
  'Từ điển',
  'Bảng đen',
  'Đồng hồ học tập',
  'Bộ công cụ học tập',
  'Bộ thí nghiệm khoa học',
  'Dụng cụ vẽ',
  'Bộ sách học tiếng Anh',
  'Chương trình học trực tuyến',
  'Đề thi',
  'Bộ bài học',
  'Vở bài tập',
  'Đồng hồ thông minh học tập',
  'Máy tính bảng học tập',
  'Bảng tương tác',
  'Bộ công cụ sáng tạo',
  'Sách tham khảo',
  'Bộ giáo cụ Montessori',
  'Giấy',
  'Bảng tính',
  'Bộ câu hỏi trắc nghiệm',
  'Vật liệu học STEM',
  'Bộ học toán',
  'Bộ học tiếng Anh',
  'Bảng chữ cái',
  'Đồ chơi giáo dục',
  'Bộ ghép hình',
  'Bộ xếp hình',
  'Bộ thẻ học từ vựng',
  'Phần mềm học',
  'Bộ sách thiếu nhi',
  'Bộ tài liệu học tiếng Anh',
  'Bảng học',
  'Bảng toán',
  'Bảng học tiếng Anh',
  'Bộ thẻ học số',
  'Sách dạy kỹ năng mềm',
  'Tài liệu học trực tuyến',
  'Bộ học chữ',
  'Bộ giáo cụ lập trình',
  'Dụng cụ học lập trình',
  'Sách bài tập',
  'Bộ đồ chơi trí tuệ',
  'Sách khoa học',
  'Sách lịch sử',
  'Sách văn học',
  'Sách đạo đức',
  'Tài liệu học trực quan',
  'Bảng vẽ',
  'Thước kẻ',
  'Sách hướng dẫn',
  'Sách học sinh',
  'Bộ sách tự học',
  'Bảng kiểm tra',
  'Bộ thí nghiệm vật lý',
  'Bộ thí nghiệm hóa học',
  'Sách toán',
  'Bộ sách ngữ văn',
  'Bộ học về thiên nhiên',
  'Bộ học về động vật',
  'Sách nghiên cứu',
  'Sách sáng tạo',
  'Dụng cụ vẽ tranh',
  'Công cụ học ngoại ngữ',
  'Sách học lập trình',
  'Bộ thẻ học ngữ pháp',
  'Sách giáo viên',
  'Phần mềm học ngoại ngữ',
  'Bảng dạy học sinh',
  'Thẻ học ngoại ngữ',
  'Bộ học về nghệ thuật',
  'Sách kỹ năng sống',
  'Bộ giáo cụ học toán',
  'Tài liệu ôn thi',
  'Bộ sách giải trí học tập',
  'Công cụ học tập STEM',
  'Sách lịch sử địa lý',
  'Bộ sách giáo dục giới tính',
  'Sách học về môi trường',
  'Bộ học về sức khỏe',
  'Dụng cụ học vật lý',
  'Phần mềm học toán',
  'Bộ sách nghệ thuật',
  'Sách nghiên cứu khoa học',
  'Bộ tài liệu kỹ năng học tập',
  'Bộ sách giải toán',
  'Bộ thí nghiệm sinh học',
  'Phần mềm học lập trình'
];

const getAccounts = async () => {
  const accounts = await Account.find({ role: 'User' }).select('_id');
  return accounts;
};

const seedProduct = async (accounts) => {
  const accountsAmount = accounts.length;

  return {
    approved: faker.datatype.boolean(),
    title:
      faker.helpers.arrayElement(noun) +
      ' ' +
      faker.helpers.arrayElement(adj) +
      ' và ' +
      faker.helpers.arrayElement(adj) +
      ' từ ' +
      faker.company.name(),
    tag: faker.helpers.arrayElements(tags, { min: 2, max: 5 }),
    description: faker.helpers.arrayElement(descriptions),
    price: faker.commerce.price({ min: 1, max: 1000, decimal: 0 }) * 1000,
    discountPercentage: faker.datatype.boolean() ? faker.number.int({ min: 0, max: 60 }) : 0,
    stock: faker.number.int({ min: 10, max: 200 }),
    sold: faker.number.int({ min: 0, max: 100 }),
    thumbnail: faker.helpers.arrayElement(thumbUrls),
    images: faker.helpers.arrayElements(regularUrls, { min: 3, max: 5 }),
    createdBy: accounts[faker.number.int({ min: 0, max: accountsAmount - 1 })],
    createdAt: faker.date.past(),
    lastModifiedAt: faker.date.recent({ days: 30 })
  };
};

const dbSeedProduct = async ({ total, seed }) => {
  const accounts = await getAccounts();

  if (seed) {
    setSeedFaker(seed);
  }

  const productsPromises = Array.from({ length: total }).map(() => seedProduct(accounts));
  const products = (await Promise.all(productsPromises)).map((product) => new Product(product));

  try {
    await Product.bulkSave(products);
  } catch (err) {
    console.log(
      '\x1b[36m%s\x1b[0m', //cyan
      '[SEEDING] Seeding failed. Drop the collection/database and try again? Or try another seed value.'
    );
    throw err;
  }
  console.log(`Seeded ${total} products with seed ${seed}`);
};

module.exports = dbSeedProduct;
